# Generated by Django 5.1.3 on 2024-11-06 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venezuela_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='genre',
        ),
        migrations.AddField(
            model_name='videogame',
            name='developers',
            field=models.ManyToManyField(to='venezuela_games.developer'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='game_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venezuela_games.gameengine'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='genres',
            field=models.ManyToManyField(to='venezuela_games.genre'),
        ),
    ]
